services:
  - type: web
    name: bibliomanga-web
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        sync: false
      - key: DATABASE_URL
        sync: false